### ISSUE TITLE
How to import css file

### ISSUE THREAD

**Issue by ansarizafar** [Shopify/slate#133]
I am trying to import semantic.css [(Semantic-ui)](semantic-ui.com) file from styles/vendor folder in theme.scss file but I am getting error in browser console file not theme.scss.css file not found

**Comment by adrhumphreys** [comment]
@ansarizafar can you show us the code you're using to try an accomplish this? It really helps to try and solve it

**Comment by ansarizafar** [comment]
@adrhumphreys I have not made any change in code. Here are the steps to reproduce the issue.

Slate theme test
Rename and update config.sample.yml
```
development:
  password: b261a6ca7a8ad449d80bcd34e89db450
  theme_id: "171030868"
  store: "24sevenbattery.myshopify.com"
  ignore_files:

production:
  password: b261a6ca7a8ad449d80bcd34e89db450
  theme_id: "171030932"
  store: "24sevenbattery.myshopify.com"
  ignore_files:
```
Copy semantic.css to src/styles/vendor folder
Impport semantic.css file in theme.scss file
```
@import url('vendor/semantic.css');
```
slate build
slate start
Here is the error in browser console
```
https://cdn.shopify.com/s/files/1/1941/3749/t/2/assets/theme.scss.css?16730064958607135614 Failed to load resource: the server responded with a status of 422 ()
```
If I remove css from theme.scss link tag evering thing works
```
//cdn.shopify.com/s/files/1/1941/3749/t/2/assets/theme.scss?16730064958607135614
```
