### ISSUE TITLE
Local Preview Pulling from Live

### ISSUE THREAD

**Issue by baberuth22** [Shopify/slate#166]
### Problem

We have multiple developers working on a shop.   Somehow when previewing the site using localhost:3000 we are getting code crossed.   The localhost preview is pulling files from the live theme.   One developer is seeing the others theme.liquid file on localhost.

### Replication steps

Have two developers working on the same theme.

**Comment by NathanPJF** [comment]
Are both developers' `confg.yml` files pointing at the same theme ID?  If so, then this is expected behaviour.  There's no local development in Slate, when you run `slate watch` it is always deploying to your site.  https://shopify.github.io/slate/commands/#watch

> Sets up the watchers for all theme assets and deploys the compiled versions to your specified environment (default is development). Also opens a Browsersync window with live reloading after changing and saving a file.

The use of `localhost:3000` is to facilitate Browsersync.  So if both developers are pushing to the same environment, they are going to see the same theme files when they run `slate watch`.

**Comment by NathanPJF** [comment]
Closing for inactivity.

**Comment by jbsmith731** [comment]
@NathanPJF I'd love to see this issue re-opened. Creating multiple themes for development isn't ideal. There has to be a better way to accomplish local development? Is there a fix for this in the works?

**Comment by jonathanmoore** [comment]
@jbsmith731 Using the config.yml file you can have multiple developers working on various branches or states of the same theme's code.  For example, your live, published theme could be the latest version of the production code, but you can duplicate the live theme to simultaneously working on various features.

```yml
live:
  password: 0000000aaaaaaa0000000aaaaaaa
  theme_id: "live"
  store: yourshop.myshopify.com
  ignore_files:
    - settings_data.json

staging:
  password: 0000000aaaaaaa0000000aaaaaaa
  theme_id: 12222222
  store: yourshop.myshopify.com
  ignore_files:
    - settings_data.json

new-feature-a:
  password: 0000000aaaaaaa0000000aaaaaaa
  theme_id: 13333333
  store: yourshop.myshopify.com
  ignore_files:
    - settings_data.json

new-feature-b:
  password: 0000000aaaaaaa0000000aaaaaaa
  theme_id: 14444444
  store: yourshop.myshopify.com
  ignore_files:
    - settings_data.json
```

Then if you're using git branches / pull requests each developer can merge their code/features into the staging or production ready code to be pushed to the correct published or unpublished theme.
