### ISSUE TITLE
deploy command overwrites sectioned blocks

### ISSUE THREAD

**Issue by yangkennyk** [Shopify/slate#174]
Right now I have 2 environments. One staging and one production. I will use "slate watch" for my staging instance and when i'm ready I'll use "slate deploy" to my production instance.

The problem is that when I use "slate deploy" on my production instance, it resets all my blocks. 

Say I have a page on my site that has section "blocks" for news articles. I'll add the blocks though the shopify customize theme editor. Once I "slate deploy" those blocks are erased.

Is there anyway around this?

**Comment by jonathanmoore** [comment]
All you need to do is set up your `config.yml` file to ignore the settings file (`config/settings_data.json')

```
production:
  password: 0000000000000000000000000
  theme_id: 1111111111
  store: production-site.myshopify.com
  ignore_files:
    - settings_data.json
```
