### ISSUE TITLE
Block Comments in Included CSS Files Cause Compile Errors.

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate#204]
### Problem

I've found that including CSS documents that begin with large block comments cause the compiler to fail.

### Scope

*Is this an issue with Slate's theme scaffolding or its documentation?*

Probably theme scaffolding, but if known restriction then documentation.

### Replication steps

Should occur with any CSS file, but I found it by including [Featherlight & Gallery](https://github.com/noelboss/featherlight/) scripts.

### Example Comment Block

```
   /**
     * Featherlight - ultra slim jQuery lightbox
     * Version 1.7.1 - http://noelboss.github.io/featherlight/
     *
     * Copyright 2017, Noël Raoul Bossart (http://www.noelboss.com)
     * MIT Licensed.
   **/

**Comment by jonathanmoore** [comment]
This doesn't have anything to do with CSS comment blocks, Slate or even Shopify's SCSS compiler.  The comment block you added contains a UTF-8 character `ë` that is breaking the SCSS compiler.

The solution would be to add `@charset "UTF-8";` to the very top of your file to tell the SCSS compiler that you are intentionally using UTF-8 characters.  Once you do that, you can go wild with UTF-8.

```css
   /**
     * Featherlight - ultra slim jQuery lightbox
     * Version 1.7.1 - http://noelboss.github.io/featherlight/
     * 
     * Copyright 2017, Noël Raoul Bossart (http://www.noelboss.com) 💰 🍔
     * MIT Licensed.
   **/

.icon:after {
  display: inline-block;
  content: '🎉';
}
```
