### ISSUE TITLE
Sections deleted on the shopify site

### ISSUE THREAD

**Issue by pdion** [Shopify/slate#338]
### Problem

When I run _theme upload,_ all the blocks in the sections previously set on the server are deleted. 

### Replication steps

I run a slightly custom worflow:

I run _slate build_, then _theme upload_ so to not override all the files/assets on shopify - we need to keep the assets already uploaded on the site by the client when we do maintenance or development.

1. Create a section with blocks.
2. Add some blocks to the section on the Shopify shop.
3. Run _theme upload_

All blocks added are deleted.

### More Information

Any help would be appreciate, thank you.

**Comment by jonathanmoore** [comment]
All you need to do is take advantage of the config.yml settings to ignore the `settings_data.json` file.  Then you can use `slate start` and make sure the settings file isn't overwritten in the process.  

```
development:
  password: a000caaaa00ce00eb00000cb00c00b0f
  theme_id: 275480000
  store: fancy-store.myshopify.com
  ignore_files:
    - settings_data.json
```
