### ISSUE TITLE
Suggestion: multi-site, single-repository

### ISSUE THREAD

**Issue by jonathan5572** [Shopify/slate#361]
Suppose a brand has multiple stores, it'd be great if there's a way to have one code base push to multiple Shopify accounts (e.g. dev is building for English, French, and German Shopify accounts).

Something like —

```
development:
  password:
  theme_id:
  store: your-store.myshopify.com
  ignore_files:
    #- settings_data.json # Uncomment this line to avoid resetting theme settings

development-1:
  password:
  theme_id:
  store: your-store.myshopify.com
  ignore_files:
    #- settings_data.json # Uncomment this line to avoid resetting theme settings

development-2:
  password:
  theme_id:
  store: your-store.myshopify.com
  ignore_files:
    #- settings_data.json # Uncomment this line to avoid resetting theme settings
```

**Comment by Kasi-mir** [comment]
Hi Jonathan,

As per documentation, this should already be possible https://shopify.github.io/slate/commands/

Check the option variables:
> 
-e, --env  deploy to a comma-separated list of environments
> 

Is this what you looking for?

Kasimir

**Comment by jonathan5572** [comment]
@Kasi-mir Correct, but that is for different environments for a single store (dev, stage, prod), not multiple stores as per my example.

**Comment by jonathanmoore** [comment]
@jonathan5572 It does work exactly as you're describing. Most of our themes have 4-5 Shopify stores (accounts) and multiple published and unpublished themes (environments) per store.  All you need is the unique API password, store names, and theme IDs.

```
development:
  password: 77eeee7777eeee000000077777ee
  theme_id: 777007000
  store: primary-development-account.myshopify.com
  ignore_files:
    #- settings_data.json # Uncomment this line to avoid resetting theme settings

store-a-development:
  password: 88eeee8888eeee000000088888ee
  theme_id: 888008001
  store: store-a.myshopify.com
  ignore_files:
    #- settings_data.json # Uncomment this line to avoid resetting theme settings

store-a-production:
  password: 88eeee8888eeee000000088888ee
  theme_id: "live"
  store: store-a.myshopify.com
  ignore_files:
    #- settings_data.json # Uncomment this line to avoid resetting theme settings

store-b-development:
  password: 99eeee9999eeee000000099999ee
  theme_id: 999009000
  store: store-b.myshopify.com
  ignore_files:
    #- settings_data.json # Uncomment this line to avoid resetting theme settings

store-b-production:
  password: 99eeee9999eeee000000099999ee
  theme_id: "live"
  store: store-b.myshopify.com
  ignore_files:
    #- settings_data.json # Uncomment this line to avoid resetting theme settings
```
