### ISSUE TITLE
CSS fails to compile when nested ampersand in Sass

### ISSUE THREAD

**Issue by colinmeinke** [Shopify/slate#370]
If I add the following to my `theme.scss`, or any other Sass file, the CSS will fail to compile.

```scss
.foo {
  &__bar {
    background: red;
  }
}
```

From my testing it appears that any character that directly follows the ampersand will break compilation (apart from `:` as in `&:hover`).
