### ISSUE TITLE
Using liquid tags in variables.scss.liquid

### ISSUE THREAD

**Issue by jesster2k10** [Shopify/slate#421]
### Problem

I'm trying to update my variables.scss.liquid to reflect on the settings schema but when I do try to use liquid tags, I get the following error in my other scss files when I call on the variable:

`Invalid CSS after "...nt-font-family:": expected 1 selector or at-rule, was "{{ settings.accent_"`

### Replication steps

`variables.scss.liquid`
```scss
/* stylelint-disable color-no-hex */

/* ================ Color Variables ================ */
$color-primary: var(--color-primary);

// Text colors
$color-body-text: #444444;

// Backgrounds
$color-body: var(--color-main-background);

// Border colors
$color-border: #f6f6f6;

// Helper colors for form error states
$color-disabled: #000000;
$color-disabled-border: #000000;
$color-error: #000000;
$color-error-bg: #000000;
$color-success: #000000;
$color-success-bg: #000000;

/* ================ Typography Variables ================ */
$font-weight-normal: 400;
$font-weight-bold: 700;

$font-stack-header: 'HelveticaNeue', 'Helvetica Neue', helvetica, arial,
  sans-serif;
$font-weight-header: $font-weight-bold;

$font-stack-body: 'HelveticaNeue', 'Helvetica Neue', helvetica, arial,
  sans-serif;
$font-size-base: 16px;

$accent-font-family: {{ settings.accent_font_family }};
$accent-font-color: black;

/* ============================================================================
  Grid Breakpoints and Class Names
    - Do not change the variable names
============================================================================== */
$grid-medium: 750px;
$grid-large: 990px;
$grid-widescreen: 1400px;
$grid-gutter: 30px;

$small: 'small';
$medium: 'medium';
$medium-down: 'medium-down';
$medium-up: 'medium-up';
$large: 'large';
$large-down: 'large-down';
$large-up: 'large-up';
$widescreen: 'widescreen';

// The `$breakpoints` list is used to build our media queries.
// You can use these in the media-query mixin.
$breakpoints: (
  $small '(max-width: #{$grid-medium - 1})',
  $medium '(min-width: #{$grid-medium}) and (max-width: #{$grid-large - 1})',
  $medium-down '(max-width: #{$grid-large - 1})',
  $medium-up '(min-width: #{$grid-medium})',
  $large '(min-width: #{$grid-large}) and (max-width: #{$grid-widescreen - 1})',
  $large-down '(max-width: #{$grid-widescreen - 1})',
  $large-up '(min-width: #{$grid-large})',
  $widescreen '(min-width: #{$grid-widescreen})'
);

/* ============================================================================
  Generate breakpoint-specific column widths and push classes
    - Default column widths: $breakpoint-has-widths: ($small, $medium-up);
    - Default is no push classes
    - Will not work if `styles/global/grid.scss` is removed
============================================================================== */
$breakpoint-has-widths: (
  $small,
  $medium-up
);
$breakpoint-has-push: ();

/* ================ Sizing Variables ================ */
$width-site: 1180px;
$gutter: 30px;

/* ================ Z-Index ================ */
$z-index-dropdown: 2;

// really high to be safe of app markup
$z-index-skip-to-content: 10000;
```

`theme.scss`
```scss
@charset 'UTF-8';

/* ============================================================================
  [replace with theme name] | Built with Slate
    - You cannot use native CSS/Sass @imports in this file without a build script
============================================================================== */
@import '~normalize.css/normalize';

/* ================ UTILS ================ */
@import './tools/mixins';

/* ================ SETTINGS ================ */
@import './settings/variables.scss.liquid';

/* ================ COMMON ================ */
@import './global/slate-reset';
@import './global/helper-classes';
@import './global/grid';
@import './global/layout';
@import './global/icons';
@import './global/rte';
@import './global/responsive-tables';
@import './global/links-buttons';
@import './global/forms';
@import './global/blank-states';

/* ================ MODULES ================ */
@import './modules/site-header';
@import './modules/gift-card-template';
```

`site-header.scss`
```scss
/* ================ Site Header ================ */
.site-logo {
  display: block;

  img {
    display: block;
    width: 100%;
  }
}

.announcment-bar {
	padding: 10px 0;
	max-height: 40px;

	div {
		font-size: 12px;
		font-family: $accent-font-family;
	}
}

.announcment-bar__url {
	text-decoration: none;
}

.navbar__container {
    margin-right: auto;
    margin-left: auto;
}

ul.nav {
	list-style-type: none;
}

li.site-nav {
	font-family: $accent-font-family;
	display: inline-block;
}

li.site-nav--active {
	font-family: $accent-font-family;
	font-weight: bold;
}

a.site-nav__link {
	text-decoration: none;
	color: $accent-font-color;
}
```

### More Information

When I changed the `theme.scss` file to `theme.scss.liquid` and updated the import in `theme.js` I get this error:

```bash
[development]: 3 / 3 [==================================================] 100 %
18:42:02 [development]Asset Perform Update to assets/styles/theme.scss.liquid at host x
	Status: 422 Unprocessable Entity
	Errors: Theme files may not be stored in subfolders
18:42:02 [development]Asset Perform Update to assets/styles/settings/variables.scss.liquid at host x
	Status: 422 Unprocessable Entity
	Errors: Theme files may not be stored in subfolders

18:42:02 [development]Asset Perform Update to assets/styles/theme.scss.liquid at host x
	Status: 422 Unprocessable Entity
	Errors: Theme files may not be stored in subfolders
18:42:02 [development]Asset Perform Update to assets/styles/settings/variables.s
```
Then on my web page, the css fails to load

`theme.js`

```javascript
import '../styles/theme.scss.liquid';

import $ from 'jquery';
import {pageLinkFocus} from '@shopify/theme-a11y';
import {cookiesEnabled} from '@shopify/theme-cart';
import {wrapTable, wrapIframe} from '@shopify/theme-rte';

window.slate = window.slate || {};
window.theme = window.theme || {};

/* = =============== Templates ================ */
// import './templates/customers-addresses';
// import './templates/customers-login.js';

$(document).ready(() => {
  // Common a11y fixes
  if (window.location.hash !== '#') {
    pageLinkFocus($(window.location.hash));
  }

  $('.in-page-link').on('click', (evt) => {
    pageLinkFocus($(evt.currentTarget.hash));
  });

  // Target tables to make them scrollable
  const tableSelectors = '.rte table';

  wrapTable({
    $tables: $(tableSelectors),
    tableWrapperClass: 'rte__table-wrapper',
  });

  // Target iframes to make them responsive
  const iframeSelectors =
    '.rte iframe[src*="youtube.com/embed"],' +
    '.rte iframe[src*="player.vimeo"]';

  wrapIframe({
    $iframes: $(iframeSelectors),
    iframeWrapperClass: 'rte__video-wrapper',
  });

  // Apply a specific class to the html element for browser support of cookies.
  if (cookiesEnabled()) {
    document.documentElement.className = document.documentElement.className.replace(
      'supports-no-cookies',
      'supports-cookies',
    );
  }
});
```

```bash
Node: v8.9.4
NPM: 5.6.0
Yarn: 1.3.2
Slate: 1.0.0-alpha.23 or 1.0.0-alpha.3
```
