### ISSUE TITLE
Enable use of non-Liquid CSS variables.

### ISSUE THREAD

**Issue by truribe** [Shopify/slate#524]
### Feature request

Please allow using pure-CSS variables in SCSS files.

### Replication steps

1. Add the following CSS to an SCSS file.  
```css
    li {
      --color: powderblue;
      background: var(--color);
    }
```
2. Run `yarn run deploy`
0. Observe the resulting error: `Module build failed: Liquid variable not found for CSS variable color`

### More Information

*Any additional information which might be helpful.*
