### ISSUE TITLE
Slate tools 0.14.0 hangs on upload of image asset

### ISSUE THREAD

**Issue by georgebutter** [Shopify/slate#616]
### Problem

When there is an update on an assets slate tools silently hangs.
This specifically happened to me with a gif file. I was able to upload the asset in the admin of the store.

### Replication steps

Setup an environment the following ignores setup in my config.yml

```
  ignore_files:
  - config/settings_data.json
  - "*.png"
  - "*.jpg"
  - "*.mp4"
  - /\.(txt|gif|bat)$/
  - untitled file
  timeout: 90s
  refill_rate: 2
  bucket_size: 40
  concurrency: 4
```
Run `slate watch`

Add a gif to the assets folder.

### More Information

I have only tested this with gif so far no other file formats.
The file size was 71kb
